import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen overflow-x-hidden">
        <ul>
          <li>
            <Link href="/multiple_dashboard">
              <a>multiple_dashboard</a>
            </Link>
          </li>
          <li>
            <Link href="/educational_dashboard">
              <a>educational_dashboard</a>
            </Link>
          </li>
          <li>
            <Link href="/medical_dashboard">
              <a>medical_dashboard</a>
            </Link>
          </li>
          <li>
            <Link href="/realstate_dashboard">
              <a>realstate_dashboard</a>
            </Link>
          </li>
          <li>
            <Link href="/rent_dashboard">
              <a>rent_dashboard</a>
            </Link>
          </li>
          <li>
            <Link href="/shop_dashbord">
              <a>shop_dashbord</a>
            </Link>
          </li>
        </ul>
      </main>
    </>
  );
}
