import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ul>
                <li>
                    <Link href="/dashboard_1">
                        <a>Dashboard 1</a>
                    </Link>
                </li>
            </ul>
        </div>
    );
}
